//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xim {
    using System;
    
    /// <exclude/>
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xim.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action template {0} cannot be bound to type {1}.
        /// </summary>
        internal static string ApiHanderTemplateInvalid {
            get {
                return ResourceManager.GetString("ApiHanderTemplateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action template does not contain any parameters.
        /// </summary>
        internal static string ApiHandlerTemplateNoParameters {
            get {
                return ResourceManager.GetString("ApiHandlerTemplateNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge cannot be empty.
        /// </summary>
        internal static string ApiHeaderChallengeEmpty {
            get {
                return ResourceManager.GetString("ApiHeaderChallengeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header name cannot be empty..
        /// </summary>
        internal static string ApiHeaderNameIsEmpty {
            get {
                return ResourceManager.GetString("ApiHeaderNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header name &quot;{0}&quot; contains invalid character &apos;{1}&apos; at index {2}..
        /// </summary>
        internal static string ApiHeaderNameIsInvalid {
            get {
                return ResourceManager.GetString("ApiHeaderNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header value &quot;{0}&quot; contains invalid character &apos;{1}&apos; at index {2}..
        /// </summary>
        internal static string ApiHeaderValueIsInvalid {
            get {
                return ResourceManager.GetString("ApiHeaderValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to format response; there is no registered media formatter.
        /// </summary>
        internal static string ApiResponseNotFormatted {
            get {
                return ResourceManager.GetString("ApiResponseNotFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid action.
        /// </summary>
        internal static string ApiRouteInvalidAction {
            get {
                return ResourceManager.GetString("ApiRouteInvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid HTTP verb.
        /// </summary>
        internal static string ApiRouteInvalidVerb {
            get {
                return ResourceManager.GetString("ApiRouteInvalidVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is empty.
        /// </summary>
        internal static string SbCbsTokenEmpty {
            get {
                return ResourceManager.GetString("SbCbsTokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token key name is invalid &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNameInvalid {
            get {
                return ResourceManager.GetString("SbCbsTokenNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not contain signed expiry &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNoExpiry {
            get {
                return ResourceManager.GetString("SbCbsTokenNoExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not contain signed key name &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNoKeyName {
            get {
                return ResourceManager.GetString("SbCbsTokenNoKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not contain signed resource &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNoResource {
            get {
                return ResourceManager.GetString("SbCbsTokenNoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not start with &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNoSas {
            get {
                return ResourceManager.GetString("SbCbsTokenNoSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token does not contain signature &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenNoSignature {
            get {
                return ResourceManager.GetString("SbCbsTokenNoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token signature is invalid &quot;{0}&quot;.
        /// </summary>
        internal static string SbCbsTokenSignatureInvalid {
            get {
                return ResourceManager.GetString("SbCbsTokenSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity with the name &quot;{0}&quot; already exists.
        /// </summary>
        internal static string SbEntityNameNotUnique {
            get {
                return ResourceManager.GetString("SbEntityNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must match the expression /{0}/.
        /// </summary>
        internal static string SbEntityNameNotValid {
            get {
                return ResourceManager.GetString("SbEntityNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscription with the name &apos;{0}&apos; already exists.
        /// </summary>
        internal static string SbTopicSubscriptionNotUnique {
            get {
                return ResourceManager.GetString("SbTopicSubscriptionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more subscriptions are null.
        /// </summary>
        internal static string SbTopicSubscriptionNull {
            get {
                return ResourceManager.GetString("SbTopicSubscriptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve {0} - simulator is not running.
        /// </summary>
        internal static string SimulatorPropertyInvalid {
            get {
                return ResourceManager.GetString("SimulatorPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State cannot transition from {0} to {1}.
        /// </summary>
        internal static string SimulatorStateCannotTransition {
            get {
                return ResourceManager.GetString("SimulatorStateCannotTransition", resourceCulture);
            }
        }
    }
}
